project_id = "eorigsiksfdadeypbept"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54322
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://eorigsiksfdadeypbept.lovable.app"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
anonymous_users_enabled = true
enable_signup = true
enable_confirmations = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.sms]
enable_signup = false
enable_confirmations = false
template = "Your code is {{ .Code }} "

[db]
enabled = true
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[edge_runtime]
enabled = true
port = 54323

[functions.create-paidly-invoice]
verify_jwt = false

[storage]
enabled = true
port = 54324
file_size_limit = "50MiB"

[studio]
enabled = true
port = 54323
api_url = "http://localhost:54321"