// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eorigsiksfdadeypbept.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVvcmlnc2lrc2ZkYWRleXBiZXB0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNjUzNjQsImV4cCI6MjA2ODg0MTM2NH0.TBbn4DZCgWAoDrZGwPNeEkYViV6jYxpi7HasAE8WcPQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});